---
package:
  name: kubespray/kpm-registry
  author: Antoine Legrand
  version: 0.21.0-rc.1
  description: kpm-registry
  license: MIT

variables:
  image: quay.io/kubespray/kpm:v0.21.0
  image_etcd: quay.io/coreos/etcd:v3.0.1
  initial_cluster: etcd=http://etcd.{{namespace}}.svc.cluster.local:2380
  svc_type: NodePort

resources:
  - file: kpm-registry-dp.yaml
    name: kpm-registry
    type: deployment

  - file: kpm-registry-svc.yaml
    name: kpm-registry
    type: svc


deploy:
  - name: base/persistent-volume-claims
    shards:
      - name: etcd-1
      - name: etcd-2
      - name: etcd-3
  - name: coreos/etcd
    shards:
      - name: 1
      - name: 2
      - name: 3
    variables:
      image: quay.io/coreos/etcd:v3.0.1
      data_volumes:
        - name: varetcd
          persistentVolumeClaim:
            claimName: pvc-etcd-{{name}}

  - name: $self
